UPDATE Company SET comp_PRIsEligibleForEquifaxData = 'Y'  WHERE comp_PRIsEligibleForEquifaxData IS NULL
Go

UPDATE NewProduct SET prod_PRDescription = 
       '<div style="font-weight:bold">Blue Book Business Report including Experian Credit Information</div><p style="margin-top:0em">Creditors—such as sellers, transporters and suppliers—use this report type for performing a high-level account evaluation, where there is typically a specific interest in current and trend facts such as pay and trade experiences. Tabular and graphic presentation of the company''s rating information makes it quick & easy to make informed decisions.</p><p>The Business Report includes:  ownership, basic company contact information such as Blue Book ID#, company name, listing location, addresses, phones, faxes, e-mails, web URLs, and alternate trade names. Also included - if available/applicable - are current headquarter rating & rating definition, headquarter rating trend, Trading Member year, recent company developments, bankruptcy events, business background, people background, business profile, financial information, year-to-date trade report summary, previous two calendar years of trade reports, trade report details for the past 18 months, the current Blue Book Score, recent Blue Book Score history, affiliated businesses, and branch locations. Select credit information such as public record information, trade payment/legal filings, and business facts provided by <span style="font-weight:bold">Experian</span>, will be included with your Business Report, as available/applicable. When used in conjunction with Blue Book data, information provided by <span style="font-weight:bold">Experian</span> can help provide a comprehensive financial picture of a company as a whole, including financial activities outside of the produce industry.</p>'
       WHERE Prod_ProductID = 47

       UPDATE NewProduct SET prod_PRDescription = 
       '<div style="font-weight:bold">Blue Book Business Report including Experian Credit Information</div><p style="margin-top:0em">Creditors—such as sellers, transporters and suppliers—use this report type for performing a high-level connection/prospect evaluation, where there is typically a specific interest in current and trend facts such as pay and trade experiences. Tabular and graphic presentation of the company''s rating information makes it quick & easy to reach informed decisions.</p><p>The Business Report includes: basic company contact information such as Blue Book ID#, company name, listing location, addresses, phones, faxes, e-mails, web URLs, ownership, and alternate trade names. Also included - if available/applicable - are current headquarter rating & rating definition, affiliated businesses, branch locations, headquarter rating trend, recent company developments, bankruptcy events, business background, people background, business profile, financial information, and year-to-date trade report summary. Select credit information such as public record information, trade payment/legal filings, and business facts provided by <span style="font-weight:bold">Experian</span>, will be included with your Business Report, as available/applicable. When used in conjunction with Blue Book data, information provided by <span style="font-weight:bold">Experian</span> can help provide a comprehensive financial picture of a company as a whole, including financial activities outside of the lumber industry.</p>'
       WHERE Prod_ProductID = 80

