USE [master]
GO

CREATE LOGIN [BBSAgentJobs] WITH PASSWORD=N'BBSI2022!', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


ALTER SERVER ROLE [sysadmin] ADD MEMBER [BBSAgentJobs]
GO

