#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Analytics.Resource", IsApplication=true)]

namespace Analytics
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060021
			public const int book1Label = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int book1Share = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int book1View = 2131099682;
			
			// aapt resource value: 0x7f06002e
			public const int btnDispatch = 2131099694;
			
			// aapt resource value: 0x7f060018
			public const int ecommerceCancel = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int ecommerceDispatch = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int ecommerceSend = 2131099671;
			
			// aapt resource value: 0x7f060037
			public const int editSocialAction = 2131099703;
			
			// aapt resource value: 0x7f060035
			public const int editSocialNetwork = 2131099701;
			
			// aapt resource value: 0x7f060039
			public const int editSocialTarget = 2131099705;
			
			// aapt resource value: 0x7f06003e
			public const int editTimingCategory = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int editTimingInterval = 2131099712;
			
			// aapt resource value: 0x7f060044
			public const int editTimingLabel = 2131099716;
			
			// aapt resource value: 0x7f060042
			public const int editTimingName = 2131099714;
			
			// aapt resource value: 0x7f060024
			public const int eventDispatch = 2131099684;
			
			// aapt resource value: 0x7f06001a
			public const int eventGroup = 2131099674;
			
			// aapt resource value: 0x7f060025
			public const int exceptionGroup = 2131099685;
			
			// aapt resource value: 0x7f06002b
			public const int exceptionLocationEdit = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int exceptionLocationLabel = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int exceptionMethodEdit = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int exceptionMethodLabel = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int exceptionTypeEdit = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int exceptionTypeLabel = 2131099686;
			
			// aapt resource value: 0x7f060031
			public const int helpPageview = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int homePageview = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int isFatalChk = 2131099692;
			
			// aapt resource value: 0x7f060005
			public const int item1Category = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int item1CurrencyCode = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int item1Name = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int item1Price = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int item1Quantity = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int item1Sku = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int item1Total = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int item2Category = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int item2CurrencyCode = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int item2Name = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int item2Price = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int item2Quantity = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int item2Sku = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int item2Total = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int itemTotal = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int orderId = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int orderIdLabel = 2131099650;
			
			// aapt resource value: 0x7f060032
			public const int pageviewDispatch = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int pageviewGroup = 2131099695;
			
			// aapt resource value: 0x7f060016
			public const int shippingCost = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int shippingCostLabel = 2131099669;
			
			// aapt resource value: 0x7f060036
			public const int socialActionLabel = 2131099702;
			
			// aapt resource value: 0x7f06003b
			public const int socialDispatch = 2131099707;
			
			// aapt resource value: 0x7f060033
			public const int socialGroup = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int socialNetworkLabel = 2131099700;
			
			// aapt resource value: 0x7f06003a
			public const int socialSend = 2131099706;
			
			// aapt resource value: 0x7f060038
			public const int socialTargetLabel = 2131099704;
			
			// aapt resource value: 0x7f060001
			public const int storeName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int storeNameLabel = 2131099648;
			
			// aapt resource value: 0x7f06003d
			public const int timingCategoryLabel = 2131099709;
			
			// aapt resource value: 0x7f060046
			public const int timingDispatch = 2131099718;
			
			// aapt resource value: 0x7f06003c
			public const int timingGroup = 2131099708;
			
			// aapt resource value: 0x7f06003f
			public const int timingIntervalLabel = 2131099711;
			
			// aapt resource value: 0x7f060043
			public const int timingLabelLabel = 2131099715;
			
			// aapt resource value: 0x7f060041
			public const int timingNameLabel = 2131099713;
			
			// aapt resource value: 0x7f060045
			public const int timingSend = 2131099717;
			
			// aapt resource value: 0x7f060014
			public const int totalTax = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int totalTaxLabel = 2131099667;
			
			// aapt resource value: 0x7f06002d
			public const int trackBtn = 2131099693;
			
			// aapt resource value: 0x7f06001b
			public const int video1Label = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int video1Pause = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int video1Play = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int video2Label = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int video2Pause = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int video2Play = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ecommerce = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int eventview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int exception = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int screenview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int social = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int timing = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int book1 = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int bookCategory = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int bookShare = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int bookView = 2131034125;
			
			// aapt resource value: 0x7f05004b
			public const int currencyCode = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int currencyCodeDefault = 2131034188;
			
			// aapt resource value: 0x7f050001
			public const int dispatch = 2131034113;
			
			// aapt resource value: 0x7f050029
			public const int ecommerceCancel = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int ecommerceSend = 2131034154;
			
			// aapt resource value: 0x7f050010
			public const int ecommerceTabName = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int eventTabName = 2131034118;
			
			// aapt resource value: 0x7f050030
			public const int exceptionLocation = 2131034160;
			
			// aapt resource value: 0x7f050035
			public const int exceptionLocationHint = 2131034165;
			
			// aapt resource value: 0x7f050031
			public const int exceptionMethod = 2131034161;
			
			// aapt resource value: 0x7f050034
			public const int exceptionMethodHint = 2131034164;
			
			// aapt resource value: 0x7f05002e
			public const int exceptionTabName = 2131034158;
			
			// aapt resource value: 0x7f050036
			public const int exceptionTrack = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int exceptionType = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int exceptionTypeHint = 2131034163;
			
			// aapt resource value: 0x7f050005
			public const int helpPath = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int homePath = 2131034116;
			
			// aapt resource value: 0x7f05002f
			public const int isFatal = 2131034159;
			
			// aapt resource value: 0x7f050019
			public const int item1Category = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int item1Name = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int item1Price = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int item1Quantity = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int item1Sku = 2131034138;
			
			// aapt resource value: 0x7f05002c
			public const int item1SkuWarning = 2131034156;
			
			// aapt resource value: 0x7f05001e
			public const int item2Category = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int item2Name = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int item2Price = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int item2Quantity = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int item2Sku = 2131034143;
			
			// aapt resource value: 0x7f05002d
			public const int item2SkuWarning = 2131034157;
			
			// aapt resource value: 0x7f050016
			public const int itemCategory = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int itemName = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int itemSku = 2131034135;
			
			// aapt resource value: 0x7f050022
			public const int itemTime = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int itemTotal = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int itemsTotal = 2131034148;
			
			// aapt resource value: 0x7f050014
			public const int orderId = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int orderIdLabel = 2131034131;
			
			// aapt resource value: 0x7f05002b
			public const int orderIdWarning = 2131034155;
			
			// aapt resource value: 0x7f050002
			public const int screenTabName = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int sendPrefix = 2131034115;
			
			// aapt resource value: 0x7f050028
			public const int shippingCost = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int shippingCostLabel = 2131034151;
			
			// aapt resource value: 0x7f050039
			public const int socialAction = 2131034169;
			
			// aapt resource value: 0x7f05003d
			public const int socialActionHint = 2131034173;
			
			// aapt resource value: 0x7f050040
			public const int socialActionWarning = 2131034176;
			
			// aapt resource value: 0x7f050038
			public const int socialNetwork = 2131034168;
			
			// aapt resource value: 0x7f05003c
			public const int socialNetworkHint = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int socialNetworkWarning = 2131034175;
			
			// aapt resource value: 0x7f05003b
			public const int socialSend = 2131034171;
			
			// aapt resource value: 0x7f050037
			public const int socialTabName = 2131034167;
			
			// aapt resource value: 0x7f05003a
			public const int socialTarget = 2131034170;
			
			// aapt resource value: 0x7f05003e
			public const int socialTargetHint = 2131034174;
			
			// aapt resource value: 0x7f050012
			public const int storeName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int storeNameLabel = 2131034129;
			
			// aapt resource value: 0x7f050042
			public const int timingCategory = 2131034178;
			
			// aapt resource value: 0x7f050046
			public const int timingCategoryHint = 2131034182;
			
			// aapt resource value: 0x7f050043
			public const int timingInterval = 2131034179;
			
			// aapt resource value: 0x7f050047
			public const int timingIntervalHint = 2131034183;
			
			// aapt resource value: 0x7f050045
			public const int timingLabel = 2131034181;
			
			// aapt resource value: 0x7f050049
			public const int timingLabelHint = 2131034185;
			
			// aapt resource value: 0x7f050044
			public const int timingName = 2131034180;
			
			// aapt resource value: 0x7f050048
			public const int timingNameHint = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int timingSend = 2131034186;
			
			// aapt resource value: 0x7f050041
			public const int timingTabName = 2131034177;
			
			// aapt resource value: 0x7f050026
			public const int totalTax = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int totalTaxLabel = 2131034149;
			
			// aapt resource value: 0x7f05000a
			public const int video1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int video2 = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int videoCategory = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int videoPause = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int videoPlay = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int ecommerce_tracker = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int global_tracker = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
