//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Blue Book.
        /// </summary>
        internal static string AdditionalBlueBook {
            get {
                return ResourceManager.GetString("AdditionalBlueBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional &lt;em&gt;Blueprints&lt;/em&gt; subscription.
        /// </summary>
        internal static string AdditionalBlueprintsSubscription {
            get {
                return ResourceManager.GetString("AdditionalBlueprintsSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Local Source licenses to access the local source growers database..
        /// </summary>
        internal static string AdditionalLocalSourceLicense {
            get {
                return ResourceManager.GetString("AdditionalLocalSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air.
        /// </summary>
        internal static string Air {
            get {
                return ResourceManager.GetString("Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annually.
        /// </summary>
        internal static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annually.
        /// </summary>
        internal static string Annually_LC {
            get {
                return ResourceManager.GetString("Annually_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Trucklot Volume (Trucklot=44,000 lbs).
        /// </summary>
        internal static string AnnualTrucklotVolume {
            get {
                return ResourceManager.GetString("AnnualTrucklotVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange transportation with (check all that apply):.
        /// </summary>
        internal static string ArrangeTransportationWith {
            get {
                return ResourceManager.GetString("ArrangeTransportationWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Number.
        /// </summary>
        internal static string AuthorizationNumber {
            get {
                return ResourceManager.GetString("AuthorizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankrupt Yes/No.
        /// </summary>
        internal static string BankruptYesNo {
            get {
                return ResourceManager.GetString("BankruptYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBOS Order Number.
        /// </summary>
        internal static string BBOSOrderNumber {
            get {
                return ResourceManager.GetString("BBOSOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Line 1.
        /// </summary>
        internal static string BillingAddressLine1 {
            get {
                return ResourceManager.GetString("BillingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address Line 2.
        /// </summary>
        internal static string BillingAddressLine2 {
            get {
                return ResourceManager.GetString("BillingAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing City.
        /// </summary>
        internal static string BillingCity {
            get {
                return ResourceManager.GetString("BillingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        internal static string BillingCountry {
            get {
                return ResourceManager.GetString("BillingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing County.
        /// </summary>
        internal static string BillingCounty {
            get {
                return ResourceManager.GetString("BillingCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        internal static string BillingPostalCode {
            get {
                return ResourceManager.GetString("BillingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing State/Province.
        /// </summary>
        internal static string BillingStateProvince {
            get {
                return ResourceManager.GetString("BillingStateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing State is required..
        /// </summary>
        internal static string BillingStateRequired {
            get {
                return ResourceManager.GetString("BillingStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Book Listing.
        /// </summary>
        internal static string BlueBookListing {
            get {
                return ResourceManager.GetString("BlueBookListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Blue Book Listing is vital to your company&apos;s success!  Businesses serving the produce supply chain rely on Blue Book&apos;s data to connect with trading partners like yours.  Provide us with your business information. We will create your company&apos;s Blue Book listing and send it to you for review/approval prior to publishing it..
        /// </summary>
        internal static string BlueBookListingVitalToSuccess {
            get {
                return ResourceManager.GetString("BlueBookListingVitalToSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Names.
        /// </summary>
        internal static string BrandNames {
            get {
                return ResourceManager.GetString("BrandNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brokers/Distributors.
        /// </summary>
        internal static string BrokersDistributors {
            get {
                return ResourceManager.GetString("BrokersDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Information.
        /// </summary>
        internal static string BusinessInformation {
            get {
                return ResourceManager.GetString("BusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Report.
        /// </summary>
        internal static string BusinessReport {
            get {
                return ResourceManager.GetString("BusinessReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Reports.
        /// </summary>
        internal static string BusinessReports {
            get {
                return ResourceManager.GetString("BusinessReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for produce suppliers, buyers, transporters, and allied service businesses who are seeking to perform a detailed evaluation of a company with specific interest in current and historical financial, pay, and rating facts..
        /// </summary>
        internal static string BusinessReport_Description {
            get {
                return ResourceManager.GetString("BusinessReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Business Report includes, if available/applicable.
        /// </summary>
        internal static string BusinessReport_IncludesIfApplicable {
            get {
                return ResourceManager.GetString("BusinessReport_IncludesIfApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;bulletListItem2&quot;&gt;Blue Book ID#&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Company name&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Listing location&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Addresses&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Phones&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Faxes&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;E-mails &amp; website &lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Principals &amp; titles&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Current company rating &amp; rating definition&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Current Blue Book Score and i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessReport_Includes_LeftCol {
            get {
                return ResourceManager.GetString("BusinessReport_Includes_LeftCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;bulletListItem2&quot;&gt;Bankruptcy events&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Personnel background&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Last three financial statements provided&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Year-to-date trade report summary&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Previous two calendar years of trade reports&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Trade report details for the past 18 months&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;Commodities handled&lt;/li&gt;
        ///&lt;li class=&quot;bulletListItem2&quot;&gt;How the company operate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessReport_Includes_RightCol {
            get {
                return ResourceManager.GetString("BusinessReport_Includes_RightCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        internal static string Clickhere {
            get {
                return ResourceManager.GetString("Clickhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodities Handled.
        /// </summary>
        internal static string CommoditiesHandled {
            get {
                return ResourceManager.GetString("CommoditiesHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodities Handled (Top 5 to 10 Fruit &amp; Vegetables You Sell/Buy).
        /// </summary>
        internal static string CommoditiesHandledTop5to10 {
            get {
                return ResourceManager.GetString("CommoditiesHandledTop5to10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Email Address.
        /// </summary>
        internal static string CompanyEmailAddress {
            get {
                return ResourceManager.GetString("CompanyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        internal static string ConfirmEmailAddress {
            get {
                return ResourceManager.GetString("ConfirmEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        internal static string Containers {
            get {
                return ResourceManager.GetString("Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Type.
        /// </summary>
        internal static string CreditCardType {
            get {
                return ResourceManager.GetString("CreditCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        internal static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Verification Value: A 3- or 4-digit code separate from the credit card number that is printed most often (not imprinted) on the back of a credit card. For American Express, the 4-digit number is printed on the front of the card, above and to the right of the embossed account number..
        /// </summary>
        internal static string CVV_Description {
            get {
                return ResourceManager.GetString("CVV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Business Established.
        /// </summary>
        internal static string DateBusinessEstablished {
            get {
                return ResourceManager.GetString("DateBusinessEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Incorporated.
        /// </summary>
        internal static string DateIncorporated {
            get {
                return ResourceManager.GetString("DateIncorporated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include key personnel, brands, commodities you specialize in, etc. to appear in your listing. Descriptive listing lines are available for a nominal annual fee. A listing specialist will provide details about the cost once your listing is submitted..
        /// </summary>
        internal static string DescriptiveListingLines_Sentence {
            get {
                return ResourceManager.GetString("DescriptiveListingLines_Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Buyers.
        /// </summary>
        internal static string DomesticBuyers {
            get {
                return ResourceManager.GetString("DomesticBuyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Shippers.
        /// </summary>
        internal static string DomesticShippers {
            get {
                return ResourceManager.GetString("DomesticShippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Van Trailers.
        /// </summary>
        internal static string DryVanTrailers {
            get {
                return ResourceManager.GetString("DryVanTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance Your Listing with Descriptive Listing Facts.
        /// </summary>
        internal static string EnhanceListingWithDescriptiveFacts {
            get {
                return ResourceManager.GetString("EnhanceListingWithDescriptiveFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type (Other).
        /// </summary>
        internal static string EntityTypeOther {
            get {
                return ResourceManager.GetString("EntityTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors on the page.
        /// </summary>
        internal static string ErrorsOnPage {
            get {
                return ResourceManager.GetString("ErrorsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate email addresses were found.  Each user must have a unique email address..
        /// </summary>
        internal static string Errors_DuplicateEmailFound {
            get {
                return ResourceManager.GetString("Errors_DuplicateEmailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When entering user information, first name, last name, and a valid email address is required..
        /// </summary>
        internal static string Errors_EmailAddressRequired {
            get {
                return ResourceManager.GetString("Errors_EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following email addresses are already associated with either current or previous BBOS licenses.  Either change the email address or contact Blue Book Services at  630 668-3500  or &lt;a href=&quot;mailto:sales@bluebookservices.com&quot;&gt;sales@bluebookservices.com&lt;/a&gt;:.
        /// </summary>
        internal static string Errors_FollowingEmailsAlreadyAssociated {
            get {
                return ResourceManager.GetString("Errors_FollowingEmailsAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following email addresses are invalid:.
        /// </summary>
        internal static string Errors_FollowingEmailsInvalid {
            get {
                return ResourceManager.GetString("Errors_FollowingEmailsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total of all checked Type of Freight must equal 100%..
        /// </summary>
        internal static string Errors_FreightTotal {
            get {
                return ResourceManager.GetString("Errors_FreightTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Month is required..
        /// </summary>
        internal static string ExpirationDate_MonthRequired {
            get {
                return ResourceManager.GetString("ExpirationDate_MonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Year is required..
        /// </summary>
        internal static string ExpirationDate_YearRequired {
            get {
                return ResourceManager.GetString("ExpirationDate_YearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Express Update&lt;/em&gt;&amp;nbsp;reports.
        /// </summary>
        internal static string ExpressUpdateReports {
            get {
                return ResourceManager.GetString("ExpressUpdateReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered daily by email, containing important changes that have occurred to all business listings including: ownership, rating, contact information and personnel information..
        /// </summary>
        internal static string ExpressUpdateReports_Description {
            get {
                return ResourceManager.GetString("ExpressUpdateReports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra services are available for purchase..
        /// </summary>
        internal static string ExtraServicesAvailableForPurchase {
            get {
                return ResourceManager.GetString("ExtraServicesAvailableForPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        internal static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked with * are required..
        /// </summary>
        internal static string FieldsMarkedAsteriskRequired {
            get {
                return ResourceManager.GetString("FieldsMarkedAsteriskRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatbed Trailers.
        /// </summary>
        internal static string FlatbedTrailers {
            get {
                return ResourceManager.GetString("FlatbedTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for your receipt.
        /// </summary>
        internal static string ForYourReceipt {
            get {
                return ResourceManager.GetString("ForYourReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Forwarder #.
        /// </summary>
        internal static string FreightForwarderNum {
            get {
                return ResourceManager.GetString("FreightForwarderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic Areas Served.
        /// </summary>
        internal static string GeographicAreasServed {
            get {
                return ResourceManager.GetString("GeographicAreasServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growers/Shippers.
        /// </summary>
        internal static string GrowersShippers {
            get {
                return ResourceManager.GetString("GrowersShippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Cover Blue Book.
        /// </summary>
        internal static string HardCoverBlueBook {
            get {
                return ResourceManager.GetString("HardCoverBlueBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains detailed listing and rating information on produce, transportation and supply/service companies in the United States and Canada..
        /// </summary>
        internal static string HardCoverBlueBook_Description {
            get {
                return ResourceManager.GetString("HardCoverBlueBook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you learn about Blue Book Services?.
        /// </summary>
        internal static string HowDidYouLearnAboutBlueBookServices {
            get {
                return ResourceManager.GetString("HowDidYouLearnAboutBlueBookServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Learned Other.
        /// </summary>
        internal static string HowLearnedOther {
            get {
                return ResourceManager.GetString("HowLearnedOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the Blue Book Membership Application &amp; Agreement.
        /// </summary>
        internal static string IAgreeToBBMembershipAgreement {
            get {
                return ResourceManager.GetString("IAgreeToBBMembershipAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you buy produce, who do you buy from?.
        /// </summary>
        internal static string IfBuyProduceFromWho {
            get {
                return ResourceManager.GetString("IfBuyProduceFromWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a produce seller, to whom do you sell?.
        /// </summary>
        internal static string IfProduceSellerToWhomDoYouSell {
            get {
                return ResourceManager.GetString("IfProduceSellerToWhomDoYouSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorporated in U.S., which state?.
        /// </summary>
        internal static string IncorporatedInUSWhichState {
            get {
                return ResourceManager.GetString("IncorporatedInUSWhichState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Trade Shows.
        /// </summary>
        internal static string IndustryTradeShows {
            get {
                return ResourceManager.GetString("IndustryTradeShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Exporters.
        /// </summary>
        internal static string InternationalExporters {
            get {
                return ResourceManager.GetString("InternationalExporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like more information about Blue Book Services Membership..
        /// </summary>
        internal static string IWouldLikeMoreInfoAboutBBS {
            get {
                return ResourceManager.GetString("IWouldLikeMoreInfoAboutBBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to learn more about the 10% discount Blue Book members receive at Ag.Tools, an industry service providing more than 81 million records of market data for over 500 commodities..
        /// </summary>
        internal static string LearnMoreAboutAGTools {
            get {
                return ResourceManager.GetString("LearnMoreAboutAGTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally.
        /// </summary>
        internal static string Locally {
            get {
                return ResourceManager.GetString("Locally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Source License.
        /// </summary>
        internal static string LocalSourceLicense {
            get {
                return ResourceManager.GetString("LocalSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Source Licenses.
        /// </summary>
        internal static string LocalSourceLicenses {
            get {
                return ResourceManager.GetString("LocalSourceLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single license to access an additional searchable database of 36,000+ local growers in the U.S..
        /// </summary>
        internal static string LocalSourceLicense_Description {
            get {
                return ResourceManager.GetString("LocalSourceLicense_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Wholesalers.
        /// </summary>
        internal static string LocalWholesalers {
            get {
                return ResourceManager.GetString("LocalWholesalers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo File.
        /// </summary>
        internal static string LogoFile {
            get {
                return ResourceManager.GetString("LogoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        internal static string MailingAddress {
            get {
                return ResourceManager.GetString("MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address Different than Billing Address.
        /// </summary>
        internal static string MailingAddressDifferentThanBillingAddress {
            get {
                return ResourceManager.GetString("MailingAddressDifferentThanBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address Line 1.
        /// </summary>
        internal static string MailingAddressLine1 {
            get {
                return ResourceManager.GetString("MailingAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address Line 2.
        /// </summary>
        internal static string MailingAddressLine2 {
            get {
                return ResourceManager.GetString("MailingAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing City.
        /// </summary>
        internal static string MailingCity {
            get {
                return ResourceManager.GetString("MailingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Country.
        /// </summary>
        internal static string MailingCountry {
            get {
                return ResourceManager.GetString("MailingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Country is required.
        /// </summary>
        internal static string MailingCountryRequired {
            get {
                return ResourceManager.GetString("MailingCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Postal Code.
        /// </summary>
        internal static string MailingPostalCode {
            get {
                return ResourceManager.GetString("MailingPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing State.
        /// </summary>
        internal static string MailingState {
            get {
                return ResourceManager.GetString("MailingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing State/Province.
        /// </summary>
        internal static string MailingStateProvince {
            get {
                return ResourceManager.GetString("MailingStateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing State is required.
        /// </summary>
        internal static string MailingStateRequired {
            get {
                return ResourceManager.GetString("MailingStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Zip (Postal) Code.
        /// </summary>
        internal static string MailingZipPostalCode {
            get {
                return ResourceManager.GetString("MailingZipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Fee.
        /// </summary>
        internal static string MembershipFee {
            get {
                return ResourceManager.GetString("MembershipFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscription to &lt;em&gt;Produce Blueprints&lt;/em&gt;, a magazine for fresh produce professionals..
        /// </summary>
        internal static string MembershipIncludes_1 {
            get {
                return ResourceManager.GetString("MembershipIncludes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Sheet reports – Delivered weekly reflecting important changes that have occurred to all business listings, including ownership, rating, contact information and personnel information. Delivered via e-mail to all users with a Blue Book Online Services user licesse..
        /// </summary>
        internal static string MembershipIncludes_2 {
            get {
                return ResourceManager.GetString("MembershipIncludes_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Licenses.
        /// </summary>
        internal static string MembershipLicenses {
            get {
                return ResourceManager.GetString("MembershipLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership User Setup.
        /// </summary>
        internal static string MembershipUserSetup {
            get {
                return ResourceManager.GetString("MembershipUserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 1.
        /// </summary>
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 2.
        /// </summary>
        internal static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name 3.
        /// </summary>
        internal static string Name3 {
            get {
                return ResourceManager.GetString("Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of your Bank.
        /// </summary>
        internal static string NameOfYourBank {
            get {
                return ResourceManager.GetString("NameOfYourBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        internal static string NameOnCard {
            get {
                return ResourceManager.GetString("NameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of Business.
        /// </summary>
        internal static string NatureOfBusiness {
            get {
                return ResourceManager.GetString("NatureOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of Business is required.
        /// </summary>
        internal static string NatureOfBusinessRequired {
            get {
                return ResourceManager.GetString("NatureOfBusinessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Produce/Non-Refrigerated.
        /// </summary>
        internal static string NonProduceNonRefrigerated {
            get {
                return ResourceManager.GetString("NonProduceNonRefrigerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Produce Refrigerated/Frozen.
        /// </summary>
        internal static string NonProduceRefigeratedFrozen {
            get {
                return ResourceManager.GetString("NonProduceRefigeratedFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Permanent Employees.
        /// </summary>
        internal static string NumPermanentEmployees {
            get {
                return ResourceManager.GetString("NumPermanentEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Trailers Leased.
        /// </summary>
        internal static string NumTrailersLeased {
            get {
                return ResourceManager.GetString("NumTrailersLeased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Trailers Owned.
        /// </summary>
        internal static string NumTrailersOwned {
            get {
                return ResourceManager.GetString("NumTrailersOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Trucks Leased.
        /// </summary>
        internal static string NumTrucksLeased {
            get {
                return ResourceManager.GetString("NumTrucksLeased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Trucks Owned.
        /// </summary>
        internal static string NumTrucksOwned {
            get {
                return ResourceManager.GetString("NumTrucksOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Units - enter how many of each, if applicable.
        /// </summary>
        internal static string NumUnitsEnterHowManyOfEach {
            get {
                return ResourceManager.GetString("NumUnitsEnterHowManyOfEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean.
        /// </summary>
        internal static string Ocean {
            get {
                return ResourceManager.GetString("Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required fields are missing..
        /// </summary>
        internal static string OneOrMoreRequiredFieldsMissing {
            get {
                return ResourceManager.GetString("OneOrMoreRequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment &amp; Blue Book Listing.
        /// </summary>
        internal static string PaymentAndBlueBookListing {
            get {
                return ResourceManager.GetString("PaymentAndBlueBookListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Processed.
        /// </summary>
        internal static string PaymentProcessed {
            get {
                return ResourceManager.GetString("PaymentProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Ownership.
        /// </summary>
        internal static string PctOfOwnership {
            get {
                return ResourceManager.GetString("PctOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piggyback Trailers.
        /// </summary>
        internal static string PiggybackTrailers {
            get {
                return ResourceManager.GetString("PiggybackTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please print this page for your records.  A confirmation email has also been sent to {0}..
        /// </summary>
        internal static string PleasePrintPageForRecords {
            get {
                return ResourceManager.GetString("PleasePrintPageForRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid email address below. The selected Business Report will be emailed to this address after the payment has been processed..
        /// </summary>
        internal static string PleaseProvideValidEmailForBR {
            get {
                return ResourceManager.GetString("PleaseProvideValidEmailForBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a membership..
        /// </summary>
        internal static string PleaseSelectAMembership {
            get {
                return ResourceManager.GetString("PleaseSelectAMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Express update E-mail..
        /// </summary>
        internal static string PleaseSpecifyExpressUpdateEmail {
            get {
                return ResourceManager.GetString("PleaseSpecifyExpressUpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Express update FAX..
        /// </summary>
        internal static string PleaseSpecifyExpressUpdateFax {
            get {
                return ResourceManager.GetString("PleaseSpecifyExpressUpdateFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Published Logo .jpg file..
        /// </summary>
        internal static string PleaseSpecifyPublishedLogoJPGFile {
            get {
                return ResourceManager.GetString("PleaseSpecifyPublishedLogoJPGFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principals.
        /// </summary>
        internal static string Principals {
            get {
                return ResourceManager.GetString("Principals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Were any of the above principals formerly financially interested in, or managed of, any business which became bankrupt or otherwise failed to pay indebtedness in full?.
        /// </summary>
        internal static string PrincipalsFailedToPayDebt {
            get {
                return ResourceManager.GetString("PrincipalsFailedToPayDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Receipt.
        /// </summary>
        internal static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce.
        /// </summary>
        internal static string Produce {
            get {
                return ResourceManager.GetString("Produce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCE BROKER.
        /// </summary>
        internal static string PRODUCE_BROKER {
            get {
                return ResourceManager.GetString("PRODUCE_BROKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCE BUYER.
        /// </summary>
        internal static string PRODUCE_BUYER {
            get {
                return ResourceManager.GetString("PRODUCE_BUYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCE LISTING.
        /// </summary>
        internal static string PRODUCE_LISTING {
            get {
                return ResourceManager.GetString("PRODUCE_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCE SELLER.
        /// </summary>
        internal static string PRODUCE_SELLER {
            get {
                return ResourceManager.GetString("PRODUCE_SELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLY CHAIN SERVICES.
        /// </summary>
        internal static string PRODUCE_SUPPLY_CHAIN_SERVICES {
            get {
                return ResourceManager.GetString("PRODUCE_SUPPLY_CHAIN_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Logo.
        /// </summary>
        internal static string PublishedLogo {
            get {
                return ResourceManager.GetString("PublishedLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and publish your company logo with your membership..
        /// </summary>
        internal static string PublishedLogo_Description {
            get {
                return ResourceManager.GetString("PublishedLogo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail.
        /// </summary>
        internal static string Rail {
            get {
                return ResourceManager.GetString("Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating information is provided in easy-to-interpret tables and graphs..
        /// </summary>
        internal static string RatingInfoProvidedInTablesAndGraphs {
            get {
                return ResourceManager.GetString("RatingInfoProvidedInTablesAndGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string Recalculate {
            get {
                return ResourceManager.GetString("Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A receipt has been emailed to you..
        /// </summary>
        internal static string ReceiptHasBeenEmailedToYou {
            get {
                return ResourceManager.GetString("ReceiptHasBeenEmailedToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reefer Trailers.
        /// </summary>
        internal static string ReeferTrailers {
            get {
                return ResourceManager.GetString("ReeferTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral from Company.
        /// </summary>
        internal static string ReferralFromCompany {
            get {
                return ResourceManager.GetString("ReferralFromCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral from Person.
        /// </summary>
        internal static string ReferralFromPerson {
            get {
                return ResourceManager.GetString("ReferralFromPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        internal static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales tax amount has been updated..
        /// </summary>
        internal static string SalesTaxAmountUpdated {
            get {
                return ResourceManager.GetString("SalesTaxAmountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to accurately calculate the sales tax, please select your county.
        /// </summary>
        internal static string SalesTaxPleaseSelectCounty {
            get {
                return ResourceManager.GetString("SalesTaxPleaseSelectCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMPLE LISTING.
        /// </summary>
        internal static string SampleListing {
            get {
                return ResourceManager.GetString("SampleListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Membership Options.
        /// </summary>
        internal static string SelectMembershipOptions {
            get {
                return ResourceManager.GetString("SelectMembershipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Membership Package.
        /// </summary>
        internal static string SelectMembershipPackage {
            get {
                return ResourceManager.GetString("SelectMembershipPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shipping and tax amounts depend on your company&apos;s city, state, and country location. These will&lt;br /&gt;be automatically recalculated when this order is submitted..
        /// </summary>
        internal static string ShippingAndTaxAmountsDependOnLocation {
            get {
                return ResourceManager.GetString("ShippingAndTaxAmountsDependOnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        internal static string SpecialInstructions {
            get {
                return ResourceManager.GetString("SpecialInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Select Membership.
        /// </summary>
        internal static string Step1SelectMembership {
            get {
                return ResourceManager.GetString("Step1SelectMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Select Options.
        /// </summary>
        internal static string Step2SelectOptions {
            get {
                return ResourceManager.GetString("Step2SelectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: User Setup.
        /// </summary>
        internal static string Step2UserSetup {
            get {
                return ResourceManager.GetString("Step2UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Payment.
        /// </summary>
        internal static string Step3Payment {
            get {
                return ResourceManager.GetString("Step3Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: User Setup.
        /// </summary>
        internal static string Step3UserSetup {
            get {
                return ResourceManager.GetString("Step3UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Payment.
        /// </summary>
        internal static string Step4Payment {
            get {
                return ResourceManager.GetString("Step4Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: Blue Book Listing.
        /// </summary>
        internal static string Step5BlueBookListing {
            get {
                return ResourceManager.GetString("Step5BlueBookListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLY LISTING.
        /// </summary>
        internal static string SUPPLY_LISTING {
            get {
                return ResourceManager.GetString("SUPPLY_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tankers.
        /// </summary>
        internal static string Tankers {
            get {
                return ResourceManager.GetString("Tankers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us the names and email addresses of the users that require access. These can be left blank for now and users can be set up in the future..
        /// </summary>
        internal static string TellUsNamesAndEmailAddresses {
            get {
                return ResourceManager.GetString("TellUsNamesAndEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your.
        /// </summary>
        internal static string ThankYouForYour {
            get {
                return ResourceManager.GetString("ThankYouForYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for purchasing a Blue Book Business Report. Businesses throughout the produce supply chain rely on business reports when evaluating existing and new accounts. We hope you find the information valuable!&lt;/p&gt;
        ///&lt;p&gt;If you have any questions on this or another business report - or on how a Blue Book Membership can benefit your business - please do not hesitate to contact one of our service representatives at 630 668-3500.&lt;/p&gt;.
        /// </summary>
        internal static string ThankYouForYourBusinessReportPurchase_Info {
            get {
                return ResourceManager.GetString("ThankYouForYourBusinessReportPurchase_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your membership purchase!.
        /// </summary>
        internal static string ThankYouForYourMembershipPurchase {
            get {
                return ResourceManager.GetString("ThankYouForYourMembershipPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;As a Blue Book Member you will benefit from real-time credit rating and marketing information that enables you to confidently and profitability grow your business.&lt;/p&gt;
        ///&lt;p&gt;We&apos;re glad to have you as a member. To learn more about the many benefits of membership, click on the Services link above. We want to help your business in as many ways as we can.&lt;/p&gt;
        ///&lt;p&gt;&lt;em&gt;Your password(s) to Blue Book Online Services (BBOS) will be emailed to you shortly. Your order also needs to be processed by one of our Blue Boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThankYouForYourMembershipPurchase_Info {
            get {
                return ResourceManager.GetString("ThankYouForYourMembershipPurchase_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To purchase, you must agree to the terms..
        /// </summary>
        internal static string ToPurchaseMustAgreeToTerms {
            get {
                return ResourceManager.GetString("ToPurchaseMustAgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To purchase, you must agree to the membership terms.  Clicking the Purchase button will charge your credit card.  Please be patient as it may take a few moments to process your order.  Only click the Purchase button once..
        /// </summary>
        internal static string ToPurchaseYouMustAgreeToTerms {
            get {
                return ResourceManager.GetString("ToPurchaseYouMustAgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Publications.
        /// </summary>
        internal static string TradePublications {
            get {
                return ResourceManager.GetString("TradePublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSPORTATION LISTING.
        /// </summary>
        internal static string TRANSPORTATION_LISTING {
            get {
                return ResourceManager.GetString("TRANSPORTATION_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Business.
        /// </summary>
        internal static string TypeOfBusiness {
            get {
                return ResourceManager.GetString("TypeOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Entity.
        /// </summary>
        internal static string TypeOfEntity {
            get {
                return ResourceManager.GetString("TypeOfEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Freight (Total equals 100%).
        /// </summary>
        internal static string TypeOfFreightTotalEquals100 {
            get {
                return ResourceManager.GetString("TypeOfFreightTotalEquals100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Countries?.
        /// </summary>
        internal static string WhatCountries {
            get {
                return ResourceManager.GetString("WhatCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this?.
        /// </summary>
        internal static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What States?.
        /// </summary>
        internal static string WhatStates {
            get {
                return ResourceManager.GetString("WhatStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you buy your produce?.
        /// </summary>
        internal static string WhereDoYouBuyYourProduce {
            get {
                return ResourceManager.GetString("WhereDoYouBuyYourProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you sell your produce?.
        /// </summary>
        internal static string WhereDoYouSellYourProduce {
            get {
                return ResourceManager.GetString("WhereDoYouSellYourProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Born.
        /// </summary>
        internal static string YearBorn {
            get {
                return ResourceManager.GetString("YearBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years at Company.
        /// </summary>
        internal static string YearsAtCompany {
            get {
                return ResourceManager.GetString("YearsAtCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years in Position.
        /// </summary>
        internal static string YearsInPosition {
            get {
                return ResourceManager.GetString("YearsInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to receive a Business Report for.
        /// </summary>
        internal static string YouHaveSelectedToReceiveBRFor {
            get {
                return ResourceManager.GetString("YouHaveSelectedToReceiveBRFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Blue Book Team.
        /// </summary>
        internal static string YourBlueBookTeam {
            get {
                return ResourceManager.GetString("YourBlueBookTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Logo.
        /// </summary>
        internal static string YourCompanyLogo {
            get {
                return ResourceManager.GetString("YourCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Logo Complimentary.
        /// </summary>
        internal static string YourCompanyLogoComplimentary {
            get {
                return ResourceManager.GetString("YourCompanyLogoComplimentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include your logo in your company’s Blue Book profile..
        /// </summary>
        internal static string YourCompanyLogo_Description {
            get {
                return ResourceManager.GetString("YourCompanyLogo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Address.
        /// </summary>
        internal static string YourEmailAddress {
            get {
                return ResourceManager.GetString("YourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First Name.
        /// </summary>
        internal static string YourFirstName {
            get {
                return ResourceManager.GetString("YourFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Name.
        /// </summary>
        internal static string YourLastName {
            get {
                return ResourceManager.GetString("YourLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Membership includes.
        /// </summary>
        internal static string YourMembershipIncludes {
            get {
                return ResourceManager.GetString("YourMembershipIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number.
        /// </summary>
        internal static string YourPhoneNumber {
            get {
                return ResourceManager.GetString("YourPhoneNumber", resourceCulture);
            }
        }
    }
}
